### ISSUE TITLE
What are those materials.clear() ? It throws error

### ISSUE THREAD

**Issue by JuhaW** [nrgsille76/blender-io-addons#3]
https://github.com/nrgsille76/blender-io-addons/blob/924333cd45b9fa3f4aaa8d3757b105b32cbdb2a2/io_autodesk_max/import_max.py#L1721

https://github.com/nrgsille76/blender-io-addons/blob/924333cd45b9fa3f4aaa8d3757b105b32cbdb2a2/io_autodesk_max/import_max.py#L1742

**Comment by nrgsille76** [comment]
It was a left over from a older version, I just forgot to remove it. It is now done in with commit 8f91354c4288dc8429e95e7246c8f8da3d727766
